package com.otectus.runictome;

import org.junit.jupiter.api.Test;

import javax.imageio.ImageIO;
import java.awt.image.BufferedImage;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.HashSet;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Set;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertTrue;

/**
 * The GUI sprite sheet is generated by {@code tools/gui/generate_gui_sheet.py} and consumed by
 * hardcoded UV constants in {@code TomeSprites}. Nothing else in the build connects the two, so a
 * sheet edited by hand -- or a sprite moved on one side but not the other -- surfaces only as
 * garbled chrome after launching the game. These tests read the shipped PNG directly, the same way
 * {@link CuriosSlotResourcesTest} reads the shipped Curios data files.
 *
 * <p>The sprite map below must mirror {@code SPRITES} in the generator and the UV constants in
 * {@code TomeSprites}. It is duplicated deliberately: that duplication is what makes drift
 * detectable.
 */
class GuiSheetTest {

    private static final Path SHEET = Path.of("src", "main", "resources", "assets", "runictome",
            "textures", "gui", "runic_tome.png");

    /**
     * {@code blitNineSliced} routes through {@code blit(loc, x, y, u, v, w, h)} and
     * {@code blitRepeating(...)}, both of which hardcode a 256x256 texture in 1.20.1. A sheet of
     * any other size silently halves or doubles every UV.
     */
    private static final int SIZE = 256;

    /** name -> {x, y, w, h, slice}; slice of -1 means the sprite is blitted 1:1. */
    private static final Map<String, int[]> SPRITES = new LinkedHashMap<>();

    static {
        SPRITES.put("PANEL", new int[]{0, 0, 96, 96, 8});
        SPRITES.put("TROUGH", new int[]{100, 0, 48, 48, 4});
        SPRITES.put("BTN_NORMAL", new int[]{152, 0, 20, 20, 4});
        SPRITES.put("BTN_HOVER", new int[]{174, 0, 20, 20, 4});
        SPRITES.put("BTN_DISABLED", new int[]{196, 0, 20, 20, 4});
        SPRITES.put("SCROLL_TRACK", new int[]{218, 0, 6, 32, 1});
        SPRITES.put("SCROLL_THUMB", new int[]{226, 0, 6, 32, 3});
        SPRITES.put("ROW_LEDGER", new int[]{0, 100, 32, 18, 4});
        SPRITES.put("ROW_HOVER", new int[]{36, 100, 32, 18, 4});
        SPRITES.put("ROW_SELECTED", new int[]{72, 100, 32, 18, 4});
        SPRITES.put("RULE", new int[]{108, 100, 32, 2, 4});
        SPRITES.put("SLOT", new int[]{0, 122, 18, 18, -1});
        SPRITES.put("ICON_COPY", new int[]{20, 122, 16, 16, -1});
        SPRITES.put("ICON_COPY_HOVER", new int[]{38, 122, 16, 16, -1});
        SPRITES.put("ICON_EXTRACT", new int[]{56, 122, 16, 16, -1});
        SPRITES.put("ICON_EXTRACT_HOVER", new int[]{74, 122, 16, 16, -1});
        SPRITES.put("STAR_FILLED", new int[]{92, 122, 8, 8, -1});
        SPRITES.put("STAR_HOLLOW", new int[]{102, 122, 8, 8, -1});
    }

    /**
     * Mirrors {@code PALETTE} in the generator, as 0xRRGGBB. Every grey here was sampled from
     * vanilla 1.20.1's generic_54.png and widgets.png; gold is the one deliberate accent.
     */
    private static final Set<Integer> PALETTE = Set.of(
            0x000000, 0x2C2C2C, 0x373737, 0x4A4A4A, 0x555555, 0x5C5C5C, 0x6F6F6F, 0x757575,
            0x8B8B8B, 0xAAAAAA, 0xAFAFAF, 0xC6C6C6, 0xD4D4D4, 0xFFFFFF, 0xFFD24D, 0xA8802A);

    private static BufferedImage sheet() throws IOException {
        assertTrue(Files.exists(SHEET), "missing GUI sheet: " + SHEET
                + " -- run 'python tools/gui/generate_gui_sheet.py'");
        BufferedImage image = ImageIO.read(SHEET.toFile());
        assertTrue(image != null, "could not decode " + SHEET);
        return image;
    }

    @Test
    void theSheetIsExactly256Square() throws IOException {
        BufferedImage image = sheet();
        assertEquals(SIZE, image.getWidth(), "blitNineSliced hardcodes a 256px texture width");
        assertEquals(SIZE, image.getHeight(), "blitNineSliced hardcodes a 256px texture height");
    }

    @Test
    void everyOpaquePixelIsAnExactPaletteColour() throws IOException {
        BufferedImage image = sheet();
        List<String> bad = new ArrayList<>();
        for (int y = 0; y < image.getHeight() && bad.size() < 5; y++) {
            for (int x = 0; x < image.getWidth() && bad.size() < 5; x++) {
                int argb = image.getRGB(x, y);
                int alpha = (argb >>> 24) & 0xFF;
                if (alpha == 0) continue;
                // Vanilla GUI art is fully opaque or fully absent; anything between means a
                // blend or an anti-aliased edit crept in.
                if (alpha != 0xFF) {
                    bad.add(String.format("partial alpha %d at (%d,%d)", alpha, x, y));
                } else if (!PALETTE.contains(argb & 0xFFFFFF)) {
                    bad.add(String.format("off-palette #%06X at (%d,%d)", argb & 0xFFFFFF, x, y));
                }
            }
        }
        assertTrue(bad.isEmpty(), "sheet has non-palette pixels: " + bad);
    }

    @Test
    void spriteRectsAreInBoundsAndDoNotOverlap() throws IOException {
        sheet();
        Map<Long, String> owner = new HashMap<>();
        List<String> clashes = new ArrayList<>();
        for (Map.Entry<String, int[]> e : SPRITES.entrySet()) {
            int[] s = e.getValue();
            assertTrue(s[0] >= 0 && s[1] >= 0 && s[0] + s[2] <= SIZE && s[1] + s[3] <= SIZE,
                    e.getKey() + " runs off the sheet");
            for (int y = s[1]; y < s[1] + s[3]; y++) {
                for (int x = s[0]; x < s[0] + s[2]; x++) {
                    String previous = owner.put((long) y * SIZE + x, e.getKey());
                    if (previous != null && clashes.size() < 5) {
                        clashes.add(e.getKey() + " overlaps " + previous + " at (" + x + "," + y + ")");
                    }
                }
            }
        }
        assertTrue(clashes.isEmpty(), "overlapping sprites: " + clashes);
    }

    /**
     * The property that is invisible until it flickers in game: {@code blitRepeating} tiles a
     * nine-slice's edge strips and centre, and for a partial tile it samples the <em>centre</em> of
     * the source slice. Any variation along a strip, or more than one colour in the middle, shows
     * up as a seam at some particular panel width and not others.
     */
    @Test
    void nineSliceStripsAndCentresAreUniform() throws IOException {
        BufferedImage image = sheet();
        List<String> seams = new ArrayList<>();

        for (Map.Entry<String, int[]> e : SPRITES.entrySet()) {
            int[] s = e.getValue();
            if (s[4] < 0) continue;
            int x = s[0], y = s[1], w = s[2], h = s[3];
            int sw = Math.min(s[4], w / 2);
            int sh = Math.min(s[4], h / 2);

            for (int j = 0; j < h; j++) {
                if (j >= sh && j < h - sh) continue; // horizontal strips only
                Set<Integer> row = new HashSet<>();
                for (int i = sw; i < w - sw; i++) row.add(image.getRGB(x + i, y + j));
                if (row.size() > 1) {
                    seams.add(e.getKey() + ": horizontal strip row " + j + " is not constant");
                }
            }

            for (int i = 0; i < w; i++) {
                if (i >= sw && i < w - sw) continue; // vertical strips only
                Set<Integer> col = new HashSet<>();
                for (int j = sh; j < h - sh; j++) col.add(image.getRGB(x + i, y + j));
                if (col.size() > 1) {
                    seams.add(e.getKey() + ": vertical strip column " + i + " is not constant");
                }
            }

            Set<Integer> centre = new HashSet<>();
            for (int j = sh; j < h - sh; j++) {
                for (int i = sw; i < w - sw; i++) centre.add(image.getRGB(x + i, y + j));
            }
            if (centre.size() > 1) {
                seams.add(e.getKey() + ": nine-slice centre has " + centre.size() + " colours");
            }
        }

        assertTrue(seams.isEmpty(), "nine-slice sprites would tile with seams: " + seams);
    }

    /**
     * Vanilla still paints its own black scrollbar track with {@code fill()} immediately before
     * {@code renderDecorations} runs, so our track is what has to hide it.
     */
    @Test
    void theScrollTrackIsFullyOpaque() throws IOException {
        BufferedImage image = sheet();
        int[] s = SPRITES.get("SCROLL_TRACK");
        for (int j = 0; j < s[3]; j++) {
            for (int i = 0; i < s[2]; i++) {
                int alpha = (image.getRGB(s[0] + i, s[1] + j) >>> 24) & 0xFF;
                assertEquals(0xFF, alpha,
                        "scroll track is transparent at (" + i + "," + j + "); vanilla's black bar "
                                + "would show through");
            }
        }
    }
}
